import { Image, type ImageStyle, type StyleProp } from "react-native"
import { useAppTheme } from "@/lib/theme/provider"

const LIGHT = require("../../assets/images/logo-mark-light.png")
const DARK = require("../../assets/images/logo-mark-dark.png")

/** mytest brand tile (generated by brand/build.mjs). Dark tile on light theme, light tile on dark. */
export function LogoMark({ size = 28, style }: { size?: number; style?: StyleProp<ImageStyle> }) {
  const { resolved } = useAppTheme()
  return (
    <Image
      accessible={false}
      source={resolved === "dark" ? DARK : LIGHT}
      style={[{ width: size, height: size }, style]}
    />
  )
}
